### ISSUE TITLE
Please activate the `Discussions` tab from the repository settings

### ISSUE THREAD

**Issue by sugatoray** [DataTalksClub/mlops-zoomcamp#1]
Please see here on how to activate the Discussions tab on GitHub. 

- https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository

This allows one to raise a query (but not a GitHub issue) in a discussion. If it is deemed that the “query” should be an issue instead of a discussion topic, that is also possible with click of a button. 

![707A88E9-D99C-43BB-8AD2-57441134C20D](https://user-images.githubusercontent.com/10201242/167794255-caaaea23-8fd5-4e5b-a5a2-02d3df68037f.jpeg)

**Comment by sugatoray** [comment]
The reason why I wanted to add a discussion topic is to share the fact that adding the Public Google calendar (for MLOps Zoomcamp) is possible from mobile phone(s) as well. 

Here’s what you need to do:

1. Open the Google calendar link in your phone’s browser (I used Google Chrome). 
2. Now, in the browser tab that was opened, look for extra menu options (typically you will find them under the ellipsis `…` sign. 
3. Tap on the ellipsis sign and from the menu options choose `Request Desktop site` and that will open the Google Calendar in a Desktop-like browser tab instead. 
4. Now you will see the option to add MLOps Calendar. Click on <kbd>add</kbd>.

**Comment by alexeygrigorev** [comment]
Thank you for the suggestions! For discussions we can use Slack.
Can you please put the instructions for using google calendars on mobile to gist or notion? Then we can attach a link in the repo

**Comment by sugatoray** [comment]
> Thank you for the suggestions! For discussions we can use Slack.
> Can you please put the instructions for using google calendars on mobile to gist or notion? Then we can attach a link in the repo

The discussions tab allows you to manage the information within the repository. I am not asking you to replace slack. Activating the discussions tab will allow you to put any other type of information within the repository, which I will recommend highly given the benefits you get right out of the box. 

If that’s too inconvenient, I will put it in my personal gist and share the link with you. 

But, imagine, as the course runs and say others also have something to share in relation to the course, a central place, maintained within this repo would probably be much better.

**Comment by sugatoray** [comment]
@alexeygrigorev Alternatively, you could also use the link to the specific comment of mine. 

- https://github.com/DataTalksClub/mlops-zoomcamp/issues/1#issuecomment-1123290078

**Comment by sugatoray** [comment]
Here is the link to my public gist: 

- https://gist.github.com/sugatoray/54720de0f37615a38b7d904d8804de71
