### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 1.3 - (Optional) Training a ride duration prediction model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#10]
Youtube video: https://www.youtube.com/watch?v=iRunifGSHFc

**Comment by CodeProcessor** [comment]
00:00 Background
01:06 Downloading dataset
01:50 Import data
03:16 Analyse data
05:15 Filter the dataset
06:00 Calculate trip duration
09:50 Check the distribution of trip duration.
14:05 Feature selection
16:23 Onehot encoding/ Dictionary Vectorizer
19:27 Setting the target variable
19:55 Training: Linear Regression
21:20 Visualise the prediction.
22:01 Evaluate the model on the training dataset.
23:32 What if there are no categorical variables?
26:00 Code restructuring
29:15 Evaluate model on validation dataset
31:01 Training: Lasso Regression Model
32:12 Training: Ridge Regression Model
32:53 Change input features
34:35 Hyperparameter tuning.
36:38 Save the model.
38:53 Summary

**Comment by amitfrancis** [comment]
Updated timecodes
