### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 4.5 - Batch: Preparing a scoring script"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#106]
Youtube video: https://www.youtube.com/watch?v=18Lbaaeigek

**Comment by AntonisCSt** [comment]
00:00 Introduction and goal 
02:00 Turn previous training notebook into applying model notebook
18:34 Turn notebook into a script
24:16 Tips for further improvements: Creating an environment and other options

**Comment by amitfrancis** [comment]
Updated timecodes
