### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 1.4 - Course overview"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#11]
Youtube video: https://www.youtube.com/watch?v=teP9KWkP6SM

**Comment by CodeProcessor** [comment]
00:00 MLOps maturity model Introduction
01:48 ML Automation Level 0 - Nothing Automated
03:00 ML Automation Level 1 - Devops, No MLOps
05:23 ML Automation Level 2 - Automated Training
07:33 ML Automation Level 3 - Automated Deployment
10:13 ML Automation Level 4 - Full MLOps
13:15 Summary

**Comment by alexeygrigorev** [comment]
Thank you!

**Comment by LoHertel** [comment]
00:00 Review Notebook
02:03 Module 1: Model Training Process
03:30 Module 2: Benefits of Experiment Tracking and Model Management	
05:47 Module 3: Reasons for ML Pipelines
06:59 Module 3: Example of an ML Pipeline
09:01 Module 4: Model Deployment
09:58 Module 5: Model Monitoring
11:23 Module 6: Best Practices
12:23 Module 7: Processes
13:02 Summary

**Comment by amitfrancis** [comment]
Updated timcodes
