### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 5.1 - Monitoring for ML-based services"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#119]
Youtube video: https://www.youtube.com/watch?v=gMiT11Bp05A

**Comment by AntonisCSt** [comment]
00:00 Introduction
02:09 Monitoring concepts
05:35 Batch vs Online serving models
07:55 Architecture of our application
14:41 Code overview
16:37 Creating our application
35:18 Running our application
37:12 Making predictions
37:46 Recap

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks!
