### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 1.5 - MLOps maturity model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#12]
Youtube video: https://www.youtube.com/watch?v=XwTH8BDGzYk

**Comment by CodeProcessor** [comment]
00:00 MLOps maturity model Introduction
01:48 ML Automation Level 0 - Nothing Automated
03:00 ML Automation Level 1 - Devops, No MLOps
05:23 ML Automation Level 2 - Automated Training
07:33 ML Automation Level 3 - Automated Deployment
10:13 ML Automation Level 4 - Full MLOps
13:15 Summary

**Comment by alexeygrigorev** [comment]
Thank you! @amitfrancis please update the video
