### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 5.5 - Batch monitoring walktrough (Prefect, MongoDB, Evidently)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#123]
Youtube video: https://www.youtube.com/watch?v=KefdYuue_FE

**Comment by dimzachar** [comment]
0:00:00 -   Create batch monitoring for online serving model.
0:00:39 -   Analyze data, store logs, calculate metrics.
0:01:21 -   Create report using Perfect on stored data.
0:02:09 -   Create analytical dashboard in batch mode.
0:02:50 -   Creating flow from tasks.
0:03:27 -   Building interactive dashboard w/ data drift analysis.
0:04:07 -   Analyzing regression performance with data drift.
0:04:53 -   Run tasks, upload targets, load data, create model, log into mongodb, create HTML report, explore tasks.
0:05:36 -   Adding target column to mongodb.
0:06:19 -   Compare model's quality with reference data.
0:07:03 -   Model performance compared over time.
0:07:43 -   Calculate features, apply model, create reference data, fetch data, get database data.
0:08:28 -   Prepare data, create JSON profile, column mapping, no undead time features.
0:09:08 -   Generating interactive HTML report with data drift and regression performance.
0:09:56 -   Create HTML report from JSON.
0:10:41 -   Run python command to generate perfect example.
0:11:31 -   Run command to see results.
0:12:16 -   Everything worked successfully!
0:13:07 -   Created data report, saved time, manga DB.
0:13:52 -   Create report with object info.
0:14:45 -   Explore metrics & HTML report in local folder.
0:15:32 -   Compare distributions of drift data.
0:16:09 -   Exploring model performance over time.
0:16:56 -   Model underestimated target for long roads. Quality of data seen.
0:17:38 -   Explore year distribution: nice/not nice, data drift, regression performance.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
