### ISSUE TITLE
Timecodes for "MLOps Zoomcamp Homework #4"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#124]
Youtube video: https://www.youtube.com/watch?v=Gzj2crFqgSI

**Comment by dimzachar** [comment]
0:00:01 -   Deploy model, read data, make predictions, write output file.
0:01:29 -   Creating right ID with year/month.
0:03:15 -  Create output file of 19MB.
0:04:50 -   Create virtual env, install packages, convert to script, rename file, clean code in VS Code.
0:06:35 -   Upload data to cloud with S3, parameterize script, predict duration for March.
0:08:03 -   Ready to run last task: build docker container w/base image & model. Answer: 16.
0:09:41 -   Create new Docker file for homework.
0:10:57 -   Build & upload cloud-ready app v1.
0:12:19 -   Predicting NYC taxi duration using model, April data from S3.
0:14:05 -   Model trained with fake labels, answer to 6th question is 9.


This video covers the process of creating a model to predict the duration of NYC taxi rides in April using data from S3. It includes deploying the model, reading data, making predictions, writing an output file, creating an ID with year/month, converting code to a script, renaming files, cleaning code in VS Code, parameterizing the script, predicting the duration for March, building a Docker container with a base image and model, creating a new Docker file for homework, building and uploading a cloud-ready app version 1, and training the model with fake labels. The answer to the 6th question is 9.

**Comment by sohgh** [comment]
ok

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
