### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6.1 - Testing Python code with pytest"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#130]
Youtube video: https://www.youtube.com/watch?v=CJp1eFQP5nk

**Comment by jralduaveuthey** [comment]
0:00 Intro
1:51 Set Up
6:09 Configure Python Tests
9:45 Fixing lambda function 
15:00 On docker 
18:09 Unit test test_base64_decode
20:58 Unit test test_predict
23:44 Unit test test_lambda_handler
26:18  Add callbacks (test_run)
30:44 Summary

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you!
