### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6.2 - Integration tests with docker-compose"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#131]
Youtube video: https://www.youtube.com/watch?v=lBX0Gl7Z1ck

**Comment by dimzachar** [comment]
0:00:00 -   Refactoring code for better testing.
0:00:36 -   Testing functionality with Docker.pi
0:01:16 -   Send request, get response, print, test, rebuild.
0:01:47 -   Testing Docker, working well.
0:02:24 -   Run model, fetch from S3, decode, test output.
0:02:54 -   Test passes: add asserts, execute.
0:03:28 -   Python built-in assert checks results.
0:03:59 -   Spotting an error in expected response.
0:04:44 -   Compare actual and expected response, print json with formatting.
0:05:26 -   Comparing dictionaries with DeepDiff.
0:06:05 -   Comparing actual and expected responses.
0:06:57 -   Type changes seen, div object printed.
0:07:31 -   Assert on empty dict, fix type changes.
0:08:10 -   Rebuild docker image, test model version, run ID, callbacks.
0:08:55 -   Checking for differences, making adjustments.
0:09:37 -   Comparing floats with tolerance for trip duration.
0:10:15 -   Only care about one significant digit.
0:10:52 -   Test passes with local model fetch.
0:11:23 -   Test model accuracy & flow.
0:11:56 -   Optimizing local file system allocation.
0:12:44 -   Load from local file system.
0:13:15 -   Create path, get model, rename, set variables.
0:14:02 -   Load model from specified location.
0:14:51 -   Create folder, move docker, download model from S3.
0:15:41 -   Downloading files to local system.
0:16:21 -   Mount model folder to container for modification.
0:17:04 -   Linking directory to container, rebuilding model, running it to check.
0:17:38 -   Testing model integration fails.
0:18:23 -   Automating tests with new model version.
0:18:58 -   Create script to automate test.
0:19:28 -   Execute script using bash command.
0:20:07 -   Change directory to script's dir.
0:20:46 -   Navigate to script directory, pip and run test docker.
0:21:32 -   Set up tests with git commit hash.
0:22:06 -   Tag image with date/time.
0:22:46 -   Create variable, change to Docker Compose, copy example.
0:23:38 -   Testing service with environment variables and ports.
0:24:19 -   Installing Docker extension, setting environment variables, mounting folder.
0:25:04 -   Building image with Dockerfile, testing execution, setting environment variables.
0:25:47 -   Building image, running service, checking run ID.
0:26:26 -   Docker Compose up takes over shell.
0:27:02 -   Run docker compose down to stop service.
0:27:42 -   Wait one second, run script, build image, start docker compose, run test.
0:28:12 -   Program finished successfully, error code 0.
0:28:47 -   Script fails with zero error code.
0:29:23 -   Terminate script on nonzero error.
0:30:08 -   Error code written to variable.
0:30:48 -   Error code nonzero, exit w/ code, check locks, assert error.
0:31:32 -   Checked locks, saw error code 1, fixed test.
0:32:06 -   Test integration, check Kinesis callback.
0:32:47 -   Testing AWS services locally.

**Comment by amitfrancis** [comment]
Updated. Thanks!
