### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6.4 - Code quality: linting and formatting"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#133]
Youtube video: https://www.youtube.com/watch?v=uImvWE-iSDQ

**Comment by dimzachar** [comment]
0:00:00 -   Explore code quality tools: linting & formatting.
0:00:36 -   Discussing PEP 8, a Python style guide.
0:01:19 -   Analyze code with pylint for errors.
0:01:51 -   Install pylint to lint Python code.
0:02:31 -   Developing with machines, pip install, pylint dot meaning.
0:03:18 -   No trailing whitespace: Violin v2.
0:03:53 -   Installing latest release of pylint.
0:04:42 -   Fixing errors with virtual env.
0:05:22 -   Analyze code with linting.
0:05:57 -   Missing function docstring; good practice to have.
0:06:32 -   Configure eyelid with pylint rc file.
0:07:21 -   Disable warning, format code, remove trailing spaces.
0:07:55 -   Configure pylint with .pylintrc and .pyproject.toml.
0:08:30 -   Configure python projects easily.
0:09:03 -   Configure pylint warnings, suppress no docstring.
0:09:59 -   Suppress lint warnings for class.
0:10:34 -   Checking for missing modules, ignoring dogs things.
0:11:09 -   Remove trailing whitespaces w/formatter & lambda.
0:11:51 -   Disable things globally with Pi Project, disable warnings locally with Pylint.
0:12:28 -   Error code 24, not zero.
0:12:59 -   Matrix X not conforming to snake case.
0:13:31 -   Disable globally, ignore warnings.
0:14:14 -   Data too long, external file.
0:14:52 -   Strip whitespace, read from date b64, fix warnings.
0:15:43 -   Fixing encoding issues with pylint.
0:16:19 -   Navigate to path leap script dir.
0:17:02 -   Debugging complex data issue.
0:17:42 -   Pylint disable line too long.
0:18:27 -   Create event.json, read text, encode UTF-8.
0:19:19 -   Resolve docker issue, ignore refactoring.
0:20:01 -   Fix formatting with Black tool.
0:20:37 -   Install two tools: black & isort.
0:21:18 -   Committing changes for linting.
0:22:01 -   Apply black to source files, output diffs.
0:22:40 -   Quotes debate: single vs double.
0:23:14 -   Removing white space, adding comma, preserving multi-line.
0:23:51 -   Test thread, comma, check help.
0:24:33 -  Connecting two lines, trailing commas added.
0:25:15 -   Unexpected behavior, comma added, whitespace edited, parenthesis removed.
0:25:50 -   Configure project Thomas with black.
0:26:42 -   Apply Black to make code nicer.
0:27:25 -   Fixing imports with isort.
0:28:07 -   Sort data with b64, json, os, imports.
0:28:47 -   Organize imports by size.
0:29:27 -   Configure iSort for project success.
0:30:14 -   Fixed sorting with isort.
0:30:58 -   Automate formatting, sorting, tests, linting.
0:31:37 -   Code passes tests, commit in next video.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
