### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6.5 - Git pre-commit hooks"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#134]
Youtube video: https://www.youtube.com/watch?v=lmMZ7Axk2T8

**Comment by dimzachar** [comment]
0:00:00 -   Welcome back to Emma's Lobzoom Camp! In this session, we discuss best engineering practices. We've covered a lot of ground!
0:00:31 -   Run tests with pre-commit hooks.
0:01:02 -   Git hooks: pre-commit, post-commit, pre-commit tool.
0:01:38 -   Install dev tools with pip.
0:02:18 -   Explore pre-commit library usage.
0:02:51 -   Run pre-commit hooks for specific folder.
0:03:23 -   Create separate repo for project.
0:03:51 -   Create config file with pre-commit tool.
0:04:28 -   Create yaml file with VS Code.
0:05:05 -   Check for pre-commit errors.
0:05:41 -   Automate pre-commit checks with hooks.
0:06:14 -   Install environment, run pre-commit.
0:06:46 -   Create git ignore, add & commit files.
0:07:24 -   Pre-commit hook modified files.
0:08:01 -   Fixed code with pre-commit hook.
0:08:53 -   Detect private keys in git hooks.
0:09:28 -   Include tools: isort, black, pylint, pi test. Use i sword, pikamid, pre-commit hook.
0:10:08 -   Fixing code, running tests.
0:10:45 -   Integrate pre-commit hooks for Python 3.9.
0:11:37 -   Run pre-commit tests with args, format, add y & tests.
0:12:26 -   Fixing git commit errors.
0:13:28 -   Test pi, break, replace, commit, trust, fail.
0:14:12 -   Reset git repo, run around black.
0:14:58 -   Fixing code formatting errors.
0:15:43 -   Git status shows modified files.
0:16:28 -   Automatically format code on commit.
0:17:05 -   Create project, use pre-commit hooks, configure Black & Pylint.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
