### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6.7 - Homework"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#158]
Youtube video: https://www.youtube.com/watch?v=WTJ5JYHIbeg

**Comment by dimzachar** [comment]
0:00:00 -   Refactor code to reduce globals.
0:01:25 -   Create main function with year, month params.
0:03:08 -   Run Python batch to download, process, create file locally.
0:04:52 -   Smoke test successful, Pi test installed.
0:06:31 -   Write tests for pre-processing logic.
0:08:10 -   Test data time object creation.
0:10:03 -   Filter data > 1min & <60min, assert df actual = df expected.
0:11:46 -   Create data frame with video location, geolocation, duration, and timestamp.
0:13:45 -   Interesting Columns Test Fails.
0:16:03 -   Comparing two data frames, not all true, duration not equal, expected result not met.
0:17:36 -   Compare columns separately w/ deepdiff.
0:19:12 -   Compare duration, check absolute difference, assert false if small.
0:20:44 -   Compare columns, discard negative, get single number.
0:22:42 -   Write integration test for S3 data.
0:24:13 -   Create S3 bucket with Docker Compose.
0:25:54 -   Configure S3 bucket for local stack.
0:27:31 -   Redefining env. vars for local testing.
0:29:14 -   Override S3 endpoint URL for parquet file.
0:31:08 -   Preparing test data for integration test.
0:32:49 -   Create data frame, import batch, define link, save to bracket.
0:34:50 -   Data prepared, script runs, verify output.
0:36:45 -   Run code with 2021, OS system, Python batch.pi, create process.
0:38:34 -   Run script, create output folder, read result data.
0:40:46 -  Sum predicted durations: 69, test diff < 0.1.
0:42:58 -   Testing integration of S3 services.
0:44:38 -   Integrate code, create bucket, set env vars, run tests, yay!


 This video is a tutorial on refactoring code to reduce globals, setting up a main function with year and month parameters, running a Python batch to download, process, and create a file locally, a smoke test and 
Pi test installed, writing tests for pre-processing logic, testing data time object creation, filtering data, creating a data frame with video location, geolocation, duration, and timestamp, comparing two data frames, comparing columns separately with deepdiff, writing an integration test for S3 data, creating an S3 bucket with Docker Compose, configuring S3 bucket for local stack, redefining environment variables for local testing, overriding S3 endpoint URL for parquet file, preparing test data for integration test, running the code with 2021, OS system, Python batch, running the script and verifying output, summing predicted durations, testing integration of S3 services, integrating code, creating a bucket, setting environment variables, and running tests.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
