### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6b.1 - Terraform: Introduction"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#159]
Youtube video: https://www.youtube.com/watch?v=zRcLgT7Qnio

**Comment by dimzachar** [comment]
0:00:00 -   Set up infrastructure for stream-based pipeline in AWS.
0:00:42 -   Trigger camera on gaming stream events.
0:01:27 -   Prerequisites and setup for AWS client.
0:02:23 -   Install, configure, and check version of AWS secret key.
0:03:35 -   Configure infra code with Terraform.
0:04:23 -   Learn data engineering basics with Zoom Camp.
0:05:14 -   Setting up stream-based AWS pipeline with Terraform.
0:06:11 -   Deploying & automating Terraform w/ CI/CD.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
