### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6b.2 - Terraform: Modules and outputs variables"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#160]
Youtube video: https://www.youtube.com/watch?v=-6scXrFcPNk

**Comment by dimzachar** [comment]
0:00:03 -   Learn about Terraform modules & variables.
0:00:53 -   Create new folder for Terraform files.
0:02:16 -   Configure infrastructure with Terraform.
0:03:10 -   Configure Terraform backend & state.
0:04:04 -   Manage resources with remote service, store state in S3 bucket.
0:04:53 -   Creating state bucket manually.
0:05:38 -   Create state bucket manually.
0:06:24 -   Create cross-env configs w/suffixes.
0:07:18 -   Configuring AWS for remote state.
0:08:12 -   Configure multiple profiles for Terraform.
0:09:03 -   Configure AWS resources with Terraform.
0:09:52 -   Install modules via AWS provider.
0:10:39 -   Configure AWS region and project ID variables.
0:11:47 -   Create ARN URLs with AWS plugin.
0:12:49 -   Fetching account ID from data source.
0:13:47 -   Fetch account ID from current identity.
0:14:42 -   Local variables are constants, project-level variables are configurable.
0:15:48 -   Trigger Lambda on new event arrival.
0:16:33 -   Create Kinesis module for config.
0:17:47 -   Add files to Git for project structure.
0:18:30 -   Create Kinesis Stream config.
0:19:29 -   Configure variables for Terraform module.
0:20:19 -   Configure stream, shards, retention, metrics, tags.
0:21:12 -   Configure stream name, start count, retention period.
0:21:57 -   Outputting ARN of AWS Kinesis Stream.
0:22:50 -   Configuring producer side of Kinesis module.
0:23:54 -   Creating a source stream with mandatory properties.
0:24:48 -   Adding properties for 48hr retention, 2 shards, stream name explained.
0:25:52 -   Fetching module & configuring variable.
0:27:00 -   Run terraform init in week 6 best practices.
0:27:51 -   Configuring AWS profile and installing plugins.
0:28:47 -   Initialize directory, download provider, run terraform plan, view execution plan.
0:29:33 -   Create infrastructure with Terraform.
0:30:26 -   Verifying existing state, adding config.
0:31:25 -   Creating infrastructure on AWS cloud.
0:32:53 -   Resource created, check data streams.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
