### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6b.5 - CI/CD: Introduction"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#163]
Youtube video: https://www.youtube.com/watch?v=OMwwZ0Z_cdk

**Comment by dimzachar** [comment]
0:00:00 -   Enjoying devops journey: CI/CD pipeline.
0:00:43 -   Automate CI/CD pipeline for service.
0:01:33 -   Continuous delivery workflow triggered on PR merge.
0:02:16 -   Define infra, build/push, deploy lambda.
0:02:55 -   Deploying app logic across environments.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
