### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6b.6 - CI/CD: Continious integration workflow"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#164]
Youtube video: https://www.youtube.com/watch?v=xkTWF9c33mU

**Comment by dimzachar** [comment]
0:00:01 -   Trigger pull request on develop branch for best practices/code directory.
0:01:58 -   Configuring env vars, defining jobs, creating VM on Ubuntu.
0:03:37 -   Automate setup of virtual env with GitHub actions.
0:05:17 -   Run tests, lint, configure Cloud env., integration tests.
0:07:20 -   Set up environment for GitHub workflow.
0:09:31 -   Configure Terraform env, track infra changes in prod env.
0:11:31 -   Change backend config & reconfigure flag.
0:13:46 -   Init step creates new state, runs terraform plan, check for changes, use feature branch.
0:15:54 -   Create a develop branch, add AWS secrets, CI workflow triggers.
0:17:43 -   Creating pull request, running workflow, checking progress, adding AWS env vars.
0:19:59 -   Fix local stack config, increase timer, TF plan success.


This video covers setting up a GitHub workflow to automate the setup of a virtual environment, running tests, linting, configuring a Cloud environment, integration tests, configuring a Terraform environment, tracking infrastructure changes in a production environment, changing backend configuration and reconfiguring flags, creating a develop branch, adding AWS secrets, and creating a pull request. It also covers fixing local stack configuration, increasing the timer, and ensuring a successful Terraform plan.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
