### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 6b.7 - CI/CD: Continious demployment"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#165]
Youtube video: https://www.youtube.com/watch?v=jCNxqXCKh2s

**Comment by dimzachar** [comment]
0:00:04 -   Create CI workflow, deploy with push, configure AWS, run terraform.
0:02:16 -   Run terraform plan, apply step with condition, auto-approve, print output values.
0:04:01 -   Creating output variables in infra.
0:06:47 -   Build Docker image for Lambda, set env vars, output ECR URI.
0:08:46 -   Maintaining image versions, blue/green deployment, building Docker images, pushing to registry, updating labra service.
0:10:46 -   Copy artifacts, set env vars, query Run ID, copy model.
0:12:59 -   Updating Lambda with environment variables and sleep timer.
0:15:31 -   Merging pull request to deploy workflow, triggering CI pipeline.
0:18:57 -   Successfully deployed production Lambda w/ fresh app logic.


This video covers the process of creating a CI workflow, deploying with push, configuring AWS, running Terraform, creating output variables in infra, building a Docker image for Lambda, maintaining image versions, performing blue/green deployment, copying artifacts, setting environment variables, querying Run ID, copying model, updating Lambda with environment variables and sleep timer, merging pull request to deploy workflow, and triggering CI pipeline, resulting in a successful deployment of a production Lambda with fresh app logic.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
