### ISSUE TITLE
Timecodes for "Homework solution Week 5 by Nakul Bajaj"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#166]
Youtube video: https://www.youtube.com/watch?v=uwGg6PE8sLg

**Comment by dimzachar** [comment]
0:00:03 -   Monitor model performance with taxi data.
0:00:53 -   Comparing model performance on unseen data.
0:01:42 -   Train models with two datasets.
0:02:27 -   Using environment variables to control model selection.
0:03:13 -   Set up environment, run prepare.py.
0:04:15 -   Activate environment, install libraries.
0:05:12 -   Install Python 2.0b, pip, virtual env.
0:06:01 -   Installing libraries with pip.
0:06:56 -   Download data sets, run script.
0:08:01 -   Prepare reference dataset file, error: "find not found".
0:09:18 -   Troubleshooting Docker services.
0:10:15 -   Test Docker Compose setup.
0:11:11 -   Services built, pinging now.
0:12:08 -   Accessing db/http, setting docker volume.
0:13:24 -   Prediction service saves data in MongoDB.
0:14:16 -   Data stored in MongoDB securely.
0:15:02 -   Save data in Docker volume safely.
0:15:40 -   Manage volumes with docker commands.
0:16:29 -   Prediction accuracy of 5000 data points.
0:17:10 -   Analyzing 2021 data with 5000 samples.
0:18:00 -   Run send data with model v1.
0:18:58 -   Installing and running Python file.
0:20:23 -   Generating report with prefect, two functions left blank.
0:21:26 -   Saving report to MongoDB, generating HTML report.
0:22:37 -   Create mobile client, save profile, generate HTML report.
0:23:50 -   Create empty collection for report.
0:25:02 -   Generate HTML report from data, save to collection.
0:26:36 -   Version control using datetime.
0:28:04 -   Generate HTML report with F-string formatting.
0:29:57 -   Model features drifted: 3.
0:31:06 -   Testing location IDs with two drifted features.
0:32:00 -   Predicting with new model, simulating Q3 results.
0:32:52 -   Update environment, model, version; restart servers.
0:33:31 -   Restarting Docker Compose, changing to v2, cleaning server.
0:34:39 -   Simulate traffic with cached data.
0:35:54 -   Generate evidently report with new model.
0:37:06 -   Prepare reference data set.
0:38:09 -   Run prefect monitoring to get latest model.
0:39:01 -   Checking new model's drift report.
0:40:04 -   Drift detected in 2005 report.
0:41:22 -   Run startup script, connect to client, extract metrics.
0:42:13 -   Retrieve metrics from profile: client.get database, collection, print.
0:43:38 -   Find Pi docs quickly: Tutorials, collections, documents.
0:44:35 -   Bulk insert data, find reports, print collection.
0:45:26 -   Extracting metrics from nested dictionary, cleaning and measuring length.
0:46:24 -   Count keys: 9.
0:47:19 -   Features drifted: 4/5.

**Comment by amitfrancis** [comment]
Updated. Thanks!
