### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 5.3 - Prepare reference and model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#219]
Youtube video: https://www.youtube.com/watch?v=IjNrkqMYQeQ

**Comment by dimzachar** [comment]
Summary:
In this video, we will be exploring the process of building a Graphene dashboard by creating various artifacts. We will begin by downloading and loading data, performing basic statistics, and calculating targets. Following that, we will delve into data preprocessing and creating a baseline model. We will then move on to selecting features and training a linear regression model. Finally, we will review the quality of our model and create a reference data set. Throughout the video, we will explain each step briefly to give you a better understanding of the process.

Key Takeaways:
- The video is about building a Graphene dashboard by creating various artifacts
- The process includes downloading and loading data, performing basic statistics, and calculating targets
- Data preprocessing and creating a baseline model will also be discussed
- The video will cover selecting features and training a linear regression model, reviewing the quality of the model, and creating a reference data set
- The video will explain each step briefly to give viewers a better understanding of the process.

Timestamps:
0:00:00 - Creating artifacts for building a Graphene dashboard.
0:04:55 - Downloading and loading data, basic statistics, target calculation.
0:08:58 - Data preprocessing and baseline model creation explained briefly.
0:13:21 - Selecting features and training linear regression model.
0:17:46 - Reviewing model quality and creating reference data set.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
