### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 5.4 - Evidently metrics calculation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#220]
Youtube video: https://www.youtube.com/watch?v=kP3lzh_HfWY

**Comment by dimzachar** [comment]
Summary:
Hello and welcome to this video where we will be discussing the creation of an Evidently report and how to use it for data analysis. We will start by reviewing the creation of the Evidently report and the metrics involved. Then we will move on to explaining how to use Evidently for data analysis. We will cover topics such as data visualization and interpretation of results. Finally, we will dive into the code derivation for monitoring metrics in Evidently. This will include a step-by-step guide on how to set up the code for monitoring and how to interpret the results. By the end of this video, you will have a comprehensive understanding of how to create and utilize Evidently reports for your data analysis needs. So, let's get started!

Key Takeaways:
- The video will discuss the creation of an Evidently report and how to use it for data analysis
- It will cover the creation of the report and the metrics involved, using Evidently for data analysis, data visualization and interpretation of results, and code derivation for monitoring metrics in Evidently
- The video will provide a step-by-step guide on how to set up the code for monitoring and how to interpret the results
- By the end of the video, viewers will have a comprehensive understanding of how to create and utilize Evidently reports for their data analysis needs.

Timestamps:
0:00:00 - Review of creation of Evidently report and metrics.
0:04:06 - Explanation of how to use Evidently for data analysis.
0:08:09 - Code derivation for monitoring metrics in Evidently.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
