### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 5.7 - Save Grafana Dashboard"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#223]
Youtube video: https://www.youtube.com/watch?v=-c4iumyZMyw

**Comment by dimzachar** [comment]
Summary:
In this video, we will learn how to save and reuse Grafana dashboard configurations. We will also go through the process of reloading Docker and accessing saved dashboard in Grafana. The video will cover step-by-step instructions on how to save a dashboard configuration in Grafana, how to reload Docker, and how to access the saved dashboard in Grafana. By the end of the video, you will be able to save and reuse your Grafana dashboard configurations and easily access them even after reloading Docker. This tutorial is perfect for anyone who wants to streamline their dashboard creation process and save time in the long run. So, let's get started!

Key Takeaways:
- The video is about how to save and reuse Grafana dashboard configurations
- It covers step-by-step instructions on how to save a dashboard configuration in Grafana, how to reload Docker, and how to access the saved dashboard in Grafana
- The aim is to help viewers streamline their dashboard creation process and save time in the long run.

Timestamps:
0:00:00 - Saving and reusing Grafana dashboard configurations.
0:03:13 - Reloading Docker and accessing saved dashboard in Grafana.

**Comment by amitfrancis** [comment]
Updated, thanks!
