### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 5.8 - Debugging with test suites and reports"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#224]
Youtube video: https://www.youtube.com/watch?v=sNSk3ojISh8

**Comment by dimzachar** [comment]
Summary:
In this video, the presenter discusses the use of the Evidently library for monitoring data drift and debugging. They explain how to create reports and use data drift and test suites/presets, excluding the target column, running data drift tests, and visualizing results. The video also covers how to analyze data drift using test suites and reports, and how to create a visual dashboard for data drift analysis in Python. The video concludes with a farewell and gratitude to viewers of the data course.

Key Takeaways:
- The video is about the use of the Evidently library for monitoring data drift and debugging.
- The presenter explains how to create reports and use data drift and test suites/presets, excluding the target column, running data drift tests, and visualizing results.
- The video covers how to analyze data drift using test suites and reports.
- The video explains how to create a visual dashboard for data drift analysis in Python.
- The video concludes with a farewell and gratitude to viewers of the data course.

Timestamps:
0:00:00 - Debugging with Evidently library for monitoring.
0:03:07 - Create report and use data drift & test suites/presets
0:06:56 - Excluding Target column, running data drift test, visualizing results.
0:10:42 - Analyzing data drift using test suites and reports.
0:13:42 - Visual dashboard for data drift analysis in Python.
0:16:43 - Farewell and gratitude to viewers of data course.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
