### ISSUE TITLE
The homework link is not updated (intro

### ISSUE THREAD

**Issue by irtizak** [DataTalksClub/mlops-zoomcamp#268]
The homework link still refers to 2023 folder, not 2024. I've attached the page screenshot below:
![image](https://github.com/DataTalksClub/mlops-zoomcamp/assets/6762121/0b925c22-53ce-44d5-ae8c-57800590c72f)

**Comment by BenyaSa** [comment]
Noted, what can I do about this now ?

**Comment by irtizak** [comment]
Oh i thought the team updates the issues in repo. If not its okay then. I'll close it.

**Comment by alexeygrigorev** [comment]
When you see a problem that you can easily fix, you can also open a PR, see e.g. this one #273
