### ISSUE TITLE
Homework Issue

### ISSUE THREAD

**Issue by raghav-menon** [DataTalksClub/mlops-zoomcamp#31]
Hello,

Good Morning!!

In the homework we have been asked to use the "For-Hire Vehicle Trip Records". We have been asked to train a linear regression model with Pickup and drop off location as features. But what is the target? There are only 7 columns here which are  dispatching_base_nu,  pickup_datetime , dropOff_datetime , PUlocationID, DOlocationID, SR_Flag and  Affiliated_base_number. PUlocationID and DOlocationID are the two input features and I do not see a target variable. Do we have to predict the trip duration using linear regression? Please clrify

Thanks.

Regards,
Raghav

**Comment by JJnotJimmyJohn** [comment]
Hey Raghav,

I believe you have to calculate the duration by yourself. Duration = difference between pickup time and drop off time.
