### ISSUE TITLE
pandas failed to read parquet when python=3.10 and engine=fastparquet

### ISSUE THREAD

**Issue by JJnotJimmyJohn** [DataTalksClub/mlops-zoomcamp#38]
Hey guys,

Not really an issue but in case folks having the same problem - 

When I use python 3.10 and fastparquet as the engine, I always get a "system error". Then I managed to read the data as soon as I switched to python 3.9 with pyarror as the engine.

I'm using a M1 macbook air with macOS Monterey. Sorry I forgot to capture the error, but i'll post that if i can recreate it.

**Comment by alexeygrigorev** [comment]
Python 3.10 is pretty new so I'd avoid it for the next 6 months and stick to 3.9
