### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 2.1 - Experiment tracking intro"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#39]
Youtube video: https://www.youtube.com/watch?v=MiA7LQin9c8

**Comment by rizdiaprilian** [comment]
00:21 Presentation starts, concept introduction
01:15 Experiment tracking
06:04 MLFlow
07:46 Tracking experiments with MLFlow
11:06 MLFlow demo

**Comment by Tomiwa-dev** [comment]
02:20 Why is experiment tracking so important?
03:53 Tracking experiments in spreadsheets

**Comment by amitfrancis** [comment]
Updated timecodes
