### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 2.3 - Experiment tracking with MLflow"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#41]
Youtube video: https://www.youtube.com/watch?v=iaJz-T7VWec

**Comment by rizdiaprilian** [comment]
00:44 Recap of MLflow example on the previous video
01:14 Adding hyperparameter tuning into notebook using hyperopt
03:18 Defining objective function
04:43 Defining search space
07:37 Passing information to fmin optimization method
09:05 Running experiment
10:48 Exploring experiment results
11:24 Comparing results with parallel coordinates plot
13:12 Comparing results with scatter plot
14:19 Comparing results with contour plot
15:32 Selecting the best model
17:03 Training a new model with obtained parameter
21:24 Observing new model's results

**Comment by amitfrancis** [comment]
Updated timecodes
