### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 2.4 - Model management"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#42]
Youtube video: https://www.youtube.com/watch?v=OVUPIX88q88

**Comment by rizdiaprilian** [comment]
00:04 Introduction of machine learning lifecycle
01:37 Model management
02:49 Model management in MLflow
05:09 Logging models in MLflow
12:03 Making predictions using information from MLflow artifact
14:09 Recap

**Comment by amitfrancis** [comment]
Updated timecodes
