### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 2.5 - Model registry"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#43]
Youtube video: https://www.youtube.com/watch?v=TKHU7HAvGH8

**Comment by rizdiaprilian** [comment]
00:06 Motivation
02:09 Model registry
04:34 Model analysis
07:50 Promoting selected model to model registry 
11:25 Assigning registered model to different stages
12:41 Demonstration with jupyter notebook
32:15 Recap

**Comment by amitfrancis** [comment]
Updated timecodes
