### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 3.1 - Negative engineering and workflow orchestration"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#61]
Youtube video: https://www.youtube.com/watch?v=eKzCjNXoCTc

**Comment by rizdiaprilian** [comment]
00:00 Intro
00:49 About Me
01:46 Agenda
03:12 Workflow Orchestration
03:58 Workflow Orchestration Example
04:42 Pipeline Dependencies
05:12 Points of Failure
05:54 Interconnected Pipelines
07:00 Negative Engineering

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you :)
