### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 3.2 - Introduction to Prefect 2.0"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#62]
Youtube video: https://www.youtube.com/watch?v=Yb6NJwI7bXw

**Comment by rizdiaprilian** [comment]
00:00 Prefect introduction
02:05 Common issues in orchestration 
03:42 Current state of Prefect
04:06 What Prefect looks like in code
06:38 Moving from notebook to python script
15:51 Modelling and logging
18:52 Defining functions
21:40 Testing
22:50 Training best model

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you, Rizdi!
