### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 3.3 - First Prefect flow and basics"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#63]
Youtube video: https://www.youtube.com/watch?v=MCFpURG506w

**Comment by Qfl3x** [comment]
0:00 Overview
1:18 Sample use-cases with MLflow
2:58 Installing Prefect locally
3:13 Running the file as a flow
7:21 Adding tasks
9:47 Prefect Orion UI
23:08 Parameter Validation
24:12 Conclusion

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!

**Comment by amitfrancis** [comment]
Just updated the timecodes. Thank you, Mohammed!
