### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 3.4 - Remote Prefect Orion deployment"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#64]
Youtube video: https://www.youtube.com/watch?v=ComkSIAB0k4

**Comment by rizdiaprilian** [comment]
00:40 Agenda
01:16 Adding security group rules on AWS VM instance
04:00 Preparing conda environment
04:49 Hosting an Orion instance on AWS VM 
06:09 Starting Prefect Orion
07:56 Running prefect_flow.py on remote instance
09:35 Viewing flow outputs in browser

**Comment by amitfrancis** [comment]
Updated timecodes! Thanks :)

**Comment by amitfrancis** [comment]
Updated the timecodes. Thank you!
