### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 3.5 - Deployment of Prefect flow"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#65]
Youtube video: https://www.youtube.com/watch?v=xw9JfaWPPps

**Comment by rizdiaprilian** [comment]
00:44 Basic concept discussion
01:19 Defining storage
02:30 Setting deployment specification
06:13 Running prefect_deploy.py 
09:12 Create work queue

**Comment by amitfrancis** [comment]
Updated the timecodes! Thanks :)

**Comment by amitfrancis** [comment]
Thank you, Rizdi! :)
