### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 1.1 - Introduction"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#7]
Youtube video: https://www.youtube.com/watch?v=s0uaFZSzwfI

**Comment by ashish615** [comment]
00:00 Introduction to MLOps 
00:32 Example for the course: Predicting the duration of override
01:14 Best Practice for ML Project: Design, Train and Operate
02:51 MLOps

**Comment by alexeygrigorev** [comment]
Thank you! @amitfrancis please update the timecodes

**Comment by amitfrancis** [comment]
Updated timcodes
