### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 2.6 - MLflow in practice"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#71]
Youtube video: https://www.youtube.com/watch?v=1ykg4YmbFVA

**Comment by kkauffmannf** [comment]
00:00 Scenario-1
13:00 Scenario-2

**Comment by Leoes98** [comment]
Here's an updated version:

00:00 Scenario 1
13:00 Scenario 2
19:25 Scenario 3 - Intro
23:03 Scenario 3 - AWS Setup
35:05 Scenario 3 - MLflow on AWS

**Comment by amitfrancis** [comment]
Updated the timecodes :) Thanks

**Comment by amitfrancis** [comment]
Updated the timecodes, thanks! :)
