### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 2.7 - MLflow: benefits, limitations and alternatives"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#73]
Youtube video: https://www.youtube.com/watch?v=Lugy1JPsBRY

**Comment by Leoes98** [comment]
00:00 Benefits
01:23 Issues
04:37 Limitations
06:40 Alternatives
11:01 Recap

**Comment by amitfrancis** [comment]
Updated timecodes! Thanks :)

**Comment by amitfrancis** [comment]
Updated the timecodes, thanks! :)
