### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 4.2 - Web-services: Deploying models with Flask and Docker"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#84]
Youtube video: https://www.youtube.com/watch?v=D7wfMAdgdF8

**Comment by Qfl3x** [comment]
00:00 Introduction
01:41 Pipenv environment
05:12 Flask App
16:23 gunicorn
17:52 Pipenv --dev
19:20 Docker
26:35 Conclusion

**Comment by amitfrancis** [comment]
Updated timecodes!

**Comment by amitfrancis** [comment]
Thank you :)
