### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 4.3 - Web-services: Getting the models from the model registry (MLflow)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#85]
Youtube video: https://www.youtube.com/watch?v=aewOpHSCkqI

**Comment by AntonisCSt** [comment]
00:00 Introduction
00:51 Goal and required set-up
03:13 Writing flask application with web-service mlflow
07:03 Testing and improving application
10:10 Creating scikit-learn pipeline and logging it
14:44 Why & how to become independent from the tracking server
18:27 Recap

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you!
