### ISSUE TITLE
Timecodes for "MLOps Zoomcamp 1.3 - Reading Parquet files instead of CSV"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/mlops-zoomcamp#9]
Youtube video: https://www.youtube.com/watch?v=r94QjpX9vSE

**Comment by sohil-hub** [comment]
00:00 Intro and the change in the dataset
00:31 Download and read parquet files.
01:32 Install missing dependency.
02:18 difference between parquet and CSV data

**Comment by alexeygrigorev** [comment]
Thank you!

**Comment by amitfrancis** [comment]
Updated timecodes
